[package]
name = "rscl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
svm = ["cl2"]
atomics = ["svm"]
cl2 = ["opencl-sys/CL_VERSION_2_0"]

[target.'cfg(all(not(target_os = "macos"), not(target_os = "ios")))'.features]
defaults = ["cl2"]

[dependencies]
rscl-proc = { path = "rscl-proc", version = "0.1.0" }
opencl-sys = "0.2.1"
futures =  { version = "0.3.21", optional = true }
once_cell = "1.12.0"
parking_lot = "0.12.1"
bitflags = "1"
cfg-if = "1"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["full"] }

[workspace]
members = ["rscl-proc"]