[package]
name = "rscl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscl-proc = { path = "rscl-proc", version = "0.1.0" }
opencl-sys = "0.2.1"
once_cell = "1.12.0"
bitflags = "1"

[workspace]
members = ["rscl-proc"]