name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install nightly toolchain
      run: rustup toolchain install nightly

    - name: Install clippy on nightly
      run: rustup component add clippy --toolchain nightly
      
    - name: Run checks
      run: make check
