name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Set nightly
      run: rustup override set nightly
      
    - name: Run check
      run: make check
